### ISSUE TITLE
Codecov security issue

### ISSUE THREAD

**Issue by pmk-LANL** [lanl/Draco#1055]
As a heads up, [Codecov recently had a security issue](https://about.codecov.io/security-update/) with their Bash uploader and it looks like this repository is flagged as affected under the LANL organization Codecov page. I'm noting it here in case you didn't see the emails already.

**Comment by KineticTheory** [comment]
We were notified by Codecov and I followed the recommended precautions.  My review didn't find anything in our CI environment that was concerning (#1054).

**Comment by pmk-LANL** [comment]
Great, I'll close the issue then.
