### ISSUE TITLE
PR252 causes many Jayenne and Capsaicin tests to fail

### ISSUE THREAD

**Issue by KineticTheory** [lanl/Draco#260]
Ref #252.

It is hard for me to understand how these changes could cause so many failures  Maybe we should revert the merge.

The one place that is tricky is in `CDI.cc` where I change `if(T==0.0)` to a `soft_equiv(T,0.0,2.0e-16)`.  Maybe we should use `min()` instead of `epsilon()`.

-kt

**Comment by lowrie** [comment]
It's used later as bounds[i] / T.  So it must be that bounds[i] can be very small.  Maybe compare T with each bounds[i], although it's not immediately obvious how to make this work correctly.

**Comment by KineticTheory** [comment]
Fixed by #252
