### ISSUE TITLE
Should a particle know its tracking state?

### ISSUE THREAD

**Issue by alexrlongne** [lanl/Draco#341]
Should a particle know whether it's analog, DDMC, random walk, etc.? I ask this because the particle knows several meta-state things about itself (cell, communication status, advection state) but there are still a lot of extra flags inside the transporter that get passed along with the particle that could be removed if the particle knew more about itself. I think we could include extra state data inside of the weird packed integer. From a design perspective, is it better to keep the particle state smaller and pass flags or to add more state data to the particle?

**Comment by lowrie** [comment]
Ideally, a particle should store only what's needed to be persistent across time steps (or restarts), or in other words, the minimum needed to source it as a census particle.  cell makes sense.  Things like communication status and advection state sound like things that are only needed during transporting within a time step.  On the other hand, the extra stuff is crammed in `DESCRIPTOR` (1 `int`), so it's not a big penalty.  Adding another `int` or so, if it simplifies the code, is probably worth it.

BTW, it looks like `DESCRIPTOR` contains whether it's DDMC or random walk, although there's nothing like `is_ddmc()` implemented.   analog state can depend on the cell its in, so I'm not sure that should be with the particle.

**Comment by alexrlongne** [comment]
Closing this and moving it to Jayenne, sorry for opening it in the wrong repo!
