### ISSUE TITLE
Request to confirm derivations in special_functions/F_eta.cc

### ISSUE THREAD

**Issue by KineticTheory** [lanl/Draco#475]
In #469 @RyanWollaeger comments:

> I cannot seem to derive this integrand for the number density at relativistic Fermi-Dirac distribution (unless assuming an unusual form for the degeneracy dependence on energy, say). Attached to this comment is a note attempting to derive it. Apologies for introducing any misconceptions.

Note: [fd.pdf](https://github.com/lanl/Draco/files/2388622/fd.pdf)

**Comment by RyanWollaeger** [comment]
Apologies - a few more steps were needed to derive the relationship.
See the updated note attached to this comment.
Note: [fd_2.pdf](https://github.com/lanl/Draco/files/2390560/fd_2.pdf)
