### ISSUE TITLE
Error: Can't open included file 'mpif.h'

### ISSUE THREAD

**Issue by certik** [lanl/Draco#696]
It looks like the last error that I am facing is this one:
```
...
/home/certik/repos/Draco/src/FortranChecks/f90sub/Draco_MPI.F90:22: Error: Can't open included file 'mpif.h'
CMakeFiles/Lib_FC_f90sub.dir/build.make:62: recipe for target 'CMakeFiles/Lib_FC_f90sub.dir/Draco_MPI.F90.o' failed
```
In Fortran one should not use `mpif.h`, but just the `mpi` module. My other Fortran MPI codes just work on my computer, but Draco does not seem to find the `mpi` module for some reason. One might need to change how MPI is handled by CMake, not sure right now.

**Comment by certik** [comment]
This error was fixed when I told cmake to use `FC=mpi90` like this:
```
CC=mpicc CXX=mpicxx FC=mpif90 cmake ..
```
Now everything builds.

**Comment by certik** [comment]
Before closing this issue, the installation guide should be changed to specifically say that one must set the `FC` variables properly. Currently it just says to call `cmake`: https://github.com/lanl/Draco/wiki/Development---Quick-Start. In my other projects, I actually let `cmake` to find MPI and I do not require the user to set the `FC`, `CXX` and `CC` variables. In fact Draco mostly builds without setting it (it gets to 100%), but there is this last error in this issue that needs to be ironed out.

**Comment by certik** [comment]
I can help on the Fortran side once you can reproduce it.

**Comment by david8dixon** [comment]
Does setting FC to mpif90 have the same effect as enable_language(Fortran).
I wonder if the problem is that Draco is not a Fortran project but manages
the mpi fortran targets. What I found happens is FindMPI will ignore
targets for languages that aren't enabled.

For example, I can call find_package(MPI REQUIRED) and then link against
MPI::MPI_Fortran and cmake will not tell you that it ignored that target
because you haven't enabled Fortran. It is slightly more helpful when you
are explicit:

find_package(MPI REQUIRED COMPONENTS Fortran)

David

**Comment by certik** [comment]
@david8dixon I think setting `FC=mpif90` allows `cmake` to ignore the whole `MPI` dependency, as the `mpif90` wrapper will supply the correct flags to `gfortran`. But with the default `FC=gfortran`, `cmake`'s MPI module must correctly find the `mpif90` wrapper, extract the correct options and supply them to `gfortran`. And I think, as you wrote, it doesn't do it in this case and that's why both `include mpi.f` as well as `use mpi` fail.

**Comment by KineticTheory** [comment]
While thinking about this a bit more, I think this problem is most likely attributed to LANL environments automatically appending `CPATH` with the MPI include directory.  I'll do some testing to isolate the issue.

**Comment by KineticTheory** [comment]
> While thinking about this a bit more, I think this problem is most likely attributed to LANL environments automatically appending `CPATH` with the MPI include directory. I'll do some testing to isolate the issue.

* `unset CPATH`  did not reproduce this issue.  
* I'm testing the build after unsetting `FC`, `CC` and `CXX`...
